// Generated by Gemini

package main

import (
	"context"
	"fmt"
	"path/filepath"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/util/homedir"
)

func listNamespaces() ([]string, error) {
	// Step 1: Build kubeconfig path
	// homedir.HomeDir() is helper from client-go, similar to os.UserHomeDir()
	home := homedir.HomeDir()
	// Join better than "+"
	kubeconfigPath := filepath.Join(home, ".kube", "config")

	// Step 2: Build rest.Config from kubeconfig
	// Param first is masterURL (empty = use from kubeconfig)
	// Param second is path to kubeconfig file
	config, err := clientcmd.BuildConfigFromFlags("", kubeconfigPath)
	if err != nil {
		return nil, fmt.Errorf("error building kubeconfig: %w", err)
	}

	// Step 3: Create clientset from config
	// Clientset is "door" to call all K8s API
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		return nil, fmt.Errorf("error creating clientset: %w", err)
	}

	// Step 4: Call API list namespaces
	// - context.Background(): context for API call
	// - metav1.ListOptions{}: options like label selector, limit... (empty = all)
	namespaces, err := clientset.CoreV1().Namespaces().List(
		context.Background(),
		metav1.ListOptions{},
	)
	if err != nil {
		return nil, fmt.Errorf("error listing namespaces: %w", err) // return nil, error
	}

	// Step 5: Print all namespaces
	// fmt.Println("All namespaces:")
	// for _, ns := range namespaces.Items {
	// 	fmt.Printf("  - %s\n", ns.Name)
	// }
	// Save namespace into string slice
	var namespaceList []string
	// Loop through namespaces and add to slice
	for _, ns := range namespaces.Items {
		namespaceList = append(namespaceList, ns.Name)
	}

	return namespaceList, nil
}
