# Release workflow - triggered on tag push to main branch
# Builds cross-platform binaries and creates GitHub Release
name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0, v0.1.0, etc.
      # - 'latest' # Trigger on latest tag. But not really nescessary

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # fix permission to create release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.0'

    - name: Run tests
      run: go test -v ./...

    - name: Build Linux amd64
      run: GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o kctx-linux-amd64 .

    # - name: Build Linux arm64
    #   run: GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o kctx-linux-arm64 .

    - name: Build macOS amd64
      run: GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o kctx-darwin-amd64 .

    - name: Build macOS arm64 (Apple Silicon)
      run: GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=${{ github.ref_name }}" -o kctx-darwin-arm64 .

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          kctx-linux-amd64
          kctx-darwin-amd64
          kctx-darwin-arm64
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
